version: '2.1'

services:
  cet-frontend:
    build:
      context: .
    image: cet-frontend
    container_name: cet-frontend
    environment:
    - USE_HTTPS=false
    - USE_AUTH=false
    - USE_IDAM=false
    - VALIDATION_SERVICE_URL=http://business-service:8081/validate
    - SUBMIT_SERVICE_URL=http://submit-service:8181/submit
    - PERSISTENCE_SERVICE_URL=http://persistence-service:8282/formdata
    - http_proxy=
    - https_proxy=
    - no_proxy=
    ports:
    - 3000:3000
    links:
    - business-service
    - submit-service
    - persistence-service
    depends_on:
    - business-service
    - submit-service
    - persistence-service
    networks:
      default:
        aliases:
        - https://www-local.cet.reform.hmcts.net

  business-service:
    image: cet/business-service
    container_name: business-service
    environment:
    - SERVER_PORT=8081
    - http_proxy=
    - https_proxy=
    - no_proxy=
    ports:
    - 8081:8081

  submit-service:
    image: cet/submit-service
    container_name: submit-service
    environment:
    - SERVER_PORT=8181
    - CET_MAIL_HOST=idam-postfix
    - CET_MAIL_PORT=25
    - CET_MAIL_USERNAME=localhost
    - CET_MAIL_PASSWORD=Pr0bate!23
    - CET_MAIL_SENDER=cet-application@hmcts.net
    - CET_MAIL_RECIPIENT=test.cet.inbox@gmail.com
    - CET_PERSISTENCE_HOSTNAME=persistence-service:8282
    - http_proxy=
    - https_proxy=
    - no_proxy=
    ports:
    - 8181:8181
    depends_on:
    - idam-postfix

  persistence-service:
    image: cet/persistence-service
    command: --wait-for-database 30
    container_name: persistence-service
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://persistence-service-database:5432/cet
    - CET_POSTGRESQL_HOSTNAME=persistence-service-database
    - CET_POSTGRESQL_PORT=5432
    - CET_POSTGRESQL_DATABASE=cet
    - CET_POSTGRESQL_USER=cet
    - CET_POSTGRESQL_PASSWORD=cet
    - CET_PERSISTENCE_PORT=8282
    - http_proxy=
    - https_proxy=
    - no_proxy=
    ports:
    - 8282:8282
    links:
    - persistence-service-database
    depends_on:
    - persistence-service-database

  persistence-service-database:
    image: cet/persistence-service-database
    container_name: persistence-service-database
    ports:
    - 5432:5432
    volumes:
    - persistence-service-database-data:/var/lib/postgresql/data

  idam-postfix:
    image: catatnight/postfix
    container_name: idam-postfix
    environment:
    - maildomain=localhost
    - smtp_user=localhost:Pr0bate!23
    ports:
    - 25:25

volumes:
  persistence-service-database-data:

