version: '2.1'

services:
  e2e-test:
    build:
      context: ../
      dockerfile: docker/test/Dockerfile
    container_name: cet-e2e
    environment:
    - http_proxy
    - https_proxy
    - no_proxy=
    - TEST_USE_IDAM=false
    - TEST_E2E_FRONTEND_URL=https://localhost:3000
    links:
    - cet-frontend
    depends_on:
    - cet-frontend
    volumes:
    - ./test/end-to-end/output:/opt/app/output

  cet-frontend:
    build:
      context: ../
    container_name: cet-frontend
    environment:
    - USE_IDAM=false
    - NODE_ENV=testing
    - http_proxy
    - https_proxy
    - no_proxy
    ports:
    - 3000:3000
    networks:
      default:
        aliases:
        - www-docker.cet.reform.hmcts.net
