version: '2.1'

services:
  cet-frontend:
    # build:
    #   context: ../.
    # image: cet/probabte-frontend
    image: docker.artifactory.reform.hmcts.net/cet/cet-frontend:${FRONTEND_TAG:-latest}
    container_name: cet-frontend
    environment:
    - USE_HTTPS=false
    - USE_AUTH=false
    - USE_IDAM=false
    - http_proxy
    - https_proxy
    - no_proxy
    ports:
    - 3000:3000
    networks:
      default:
        aliases:
        - https://www-local.cet.reform.hmcts.net

