apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  REFORM_ENVIRONMENT: 'aat'
#  FEES_URL: 'http://fees-register-api-aat.service.core-compute-aat.internal'
#  CLAIM_STORE_URL: 'http://cmc-claim-store-aat.service.core-compute-aat.internal'
#  DRAFT_STORE_URL: 'http://draft-store-service-aat.service.core-compute-aat.internal'
